import type { DeliveryCoverageEntry } from "@/features/delivery/types/delivery";

const KANPUR_EXPRESS_ESTIMATE = "1–2 Hours";

/** Kanpur express delivery PIN coverage — extend or replace via admin CMS later. */
export const KANPUR_EXPRESS_COVERAGE: DeliveryCoverageEntry[] = [
  {
    pincode: "208001",
    area: "Kanpur Head Post Office / Civil Lines",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208002",
    area: "Arya Nagar",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208003",
    area: "P Road",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208004",
    area: "Cooperganj / Kanpur Cantt",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208006",
    area: "Govind Nagar",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208007",
    area: "Chakeri",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208010",
    area: "Jajmau",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208011",
    area: "Kidwai Nagar",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208012",
    area: "Fazalganj",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208013",
    area: "Shyam Nagar",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208015",
    area: "Lal Bangla",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208016",
    area: "IIT Kanpur",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208017",
    area: "Kalyanpur",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208019",
    area: "Rawatpur",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208020",
    area: "Panki",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208021",
    area: "Naubasta",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208022",
    area: "Ratanlal Nagar",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208024",
    area: "Kanpur Vishwavidyalaya",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208025",
    area: "Kakadeo",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "208027",
    area: "Barra",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
  {
    pincode: "209217",
    area: "Mandhana",
    city: "Kanpur",
    regionId: "kanpur",
    mode: "express",
    estimate: KANPUR_EXPRESS_ESTIMATE,
  },
];
